name: deploy workflow
on:
  workflow_dispatch:
  push:
    branches:
      - "*"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Download Codes
        uses: actions/checkout@v3

      - name: Install NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Check Code Quality
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Download Codes
        uses: actions/checkout@v3

      - name: Install NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Test
        run: npm run test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Download Codes
        uses: actions/checkout@v3

      - name: Install NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Codes
        uses: actions/checkout@v3

      - name: Install NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Deploy
        run: echo "Deploying ..."
